<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <!--Begin Style-->
        <link rel="stylesheet" href="style.css"/>
        <!--End Style-->
        <title>Compos.In</title>        
    </head>
    
    <body>
        <!--Side menu-->
        <nav id="side-menu">   
            <div id="logo">
                Compos.In
            </div>
            <div class="side-menu-but" onclick="openFile()">Open...</div>
            <input type="file" id="files" accept=".xml" />
            <!--<input type="text"></input>-->
        </nav>
        
        <!--General Content - Generated by PHP-->
        <section id="general-content">
            <nav id="score-menu"></nav>
            <div id="score-page">
                <object id="svgPage" type="image/svg+xml" data="debug.svg" height="3700" width="1520">Error</object>
            </div>
        </section>
        <script src="score/ScoreConverter.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script>
            var svgPage = document.getElementById("svgPage");
            svgPage.width = window.innerWidth - 400;
            var score = null;

            var fileOpenBut = document.getElementById('files');
            fileOpenBut.addEventListener('change', handleFileSelect, false);

            function openFile() {
                //ajaxSend();
                fileOpenBut.click();
            }

            function handleFileSelect(evt) {
                var file = evt.target.files[0]; // FileList object
                if(!file)
                    return;

                fileOpenBut.value = ""; //clear file value to be able to open the same file if needed

                var reader = new FileReader();

                reader.onloadend = function() {
                    if(reader.readyState == 2) {
                        postFile(reader.result);
                        //console.log(reader.result);
                    }
                }

                reader.readAsText(file);
            }

            function postFile(fileText) {
                var request = $.ajax({
                    url: "openFile.php",
                    type: "post",
                    data: { file: fileText}
                });

                // Callback handler that will be called on success
                request.done(function (response, textStatus, jqXHR){
                    // Log a message to the console
                    console.log("Reponded!");
                    //console.log(JSON.parse(response));
                    showFile(response);
                });

                // Callback handler that will be called on failure
                request.fail(function (jqXHR, textStatus, errorThrown){
                    // Log the error to the console
                    console.error(
                        "The following error occurred: "+
                        textStatus, errorThrown
                    );
                });

                // Callback handler that will be called regardless
                // if the request failed or succeeded
                request.always(function () {
                    // Reenable the inputs
                    //console.log("always");
                });
            }



            function showFile(jsonStr) {
                var jsonObj = JSON.parse(jsonStr);
                var scoreObj = toComposinFormat(jsonObj);
                score.OpenFile(scoreObj);
            }



            window.onload = function() {
                var svgDoc = svgPage.contentDocument;
                score = svgDoc.documentElement;
            }

            
            /*
            window.onresize = function() {
                svgPage.width = window.innerWidth - 400;

                if(score) {
                    score.Organize(window.innerWidth - 420, 300);
                }
            }*/

        </script>

    </body>   
</html>